name = "devpilot-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
AGENT_ENDPOINT = "https://adds-alien-cordless-conservation.trycloudflare.com"

[[kv_namespaces]]
binding = "DEVPILOT_KV"
id = "e1564d2bb1504c88870ccd570aad7de1" # Real KV ID
preview_id = "yyyy-yyyy-yyyy-yyyy"

[ai]
binding = "AI"
